#!/bin/bash
aclocal -I m4
which libtoolize >/dev/null 2>&1
if [ $? -eq 0 ]; then
    libtoolize --copy --force
else
    # might have files in /usr/share
    if [ -d /usr/share/libtool ]; then
        for f in /usr/share/libtool/* ; do
            if [ ! -f $(basename ${f}) ]; then
                cp -p ${f} .
            fi
        done
    fi
fi
autoconf
autoheader
touch config.h.in
automake --foreign --add-missing --copy
rm -rf autom4te.cache
